/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type BlockBreak = {
  _type: "blockBreak";
  style?: string;
};

export type Track = {
  _type: "track";
  name: string;
  number: number;
  length: string;
  file?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
  };
  artists?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "artist";
  }>;
};

export type ReleaseDate = string;

export type MetaDescription = string;

export type QuestionAnswer = {
  _type: "questionAnswer";
  question: string;
  answer: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: Array<{
          href: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & BlockBreak)
  >;
};

export type Item = {
  _type: "item";
  name: string;
  link?: string;
};

export type Credits = {
  _type: "credits";
  title: string;
  items?: Array<
    {
      _key: string;
    } & Item
  >;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & BlockBreak)
>;

export type AccessibleImage = {
  _type: "accessibleImage";
  alt: string;
  caption?: string;
};

export type PublishingArtist = {
  _id: string;
  _type: "publishingArtist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  overview: MetaDescription;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  projects?: Array<{
    name: string;
    href?: string;
    _type: "link";
    _key: string;
  }>;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
  body?: BlockContent;
  works?: TrackList;
};

export type Legal = {
  _id: string;
  _type: "legal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  overview: MetaDescription;
  englishTitle: string;
  englishContent: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  frenchTitle: string;
  frenchContent: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Faqs = {
  _id: string;
  _type: "faqs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  category: string;
  slug: Slug;
  questions?: Array<
    {
      _key: string;
    } & QuestionAnswer
  >;
};

export type Release = {
  _id: string;
  _type: "release";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  artist?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "artist";
  }>;
  overview: MetaDescription;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  productImages: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description: BlockContent;
  releaseDate: ReleaseDate;
  releaseReference: string;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
  trackList?: TrackList;
  shopifyProductDigital: string;
  digitalProductFormat: string;
  shopifyProductPhysical: string;
  physicalProductFormat: string;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type TrackList = {
  _type: "trackList";
  tracks?: Array<
    {
      _key: string;
    } & Track
  >;
};

export type Artist = {
  _id: string;
  _type: "artist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  overview: MetaDescription;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  links?: Array<
    {
      _key: string;
    } & Link
  >;
  body?: BlockContent;
  releases?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "release";
  }>;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Seo = {
  _id: string;
  _type: "seo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  twitterSite: string;
  keywords: string;
  followLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  cataloguePageTitle: string;
};

export type Publishing = {
  _id: string;
  _type: "publishing";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  overview: MetaDescription;
  creativeServicesSection?: ContentSection;
  scoreSection?: ContentSection;
  syncSection?: ContentSection;
  licenseRequestEmail: string;
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  overview: MetaDescription;
  generalSection?: ContentSection;
  locations: Array<{
    type: string;
    name: string;
    phone?: string;
    _type: "location";
    _key: string;
  }>;
  listenLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  followLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  pressKit?: Link;
  demoSection?: ContentSection;
  syncSection?: ContentSection;
};

export type Link = {
  _type: "link";
  name: string;
  href: string;
};

export type ContentSection = {
  _type: "contentSection";
  title: string;
  content: BlockContent;
  link?: Link;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  overview: MetaDescription;
  part1: BlockContent;
  part2: TwoColumn;
  part3: BlockContent;
  part4: TwoColumn;
  part5: BlockContent;
};

export type TwoColumn = {
  _type: "twoColumn";
  left?: Array<
    {
      _key: string;
    } & Credits
  >;
  right?: Array<
    {
      _key: string;
    } & Credits
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | Geopoint
  | BlockBreak
  | Track
  | ReleaseDate
  | MetaDescription
  | QuestionAnswer
  | Item
  | Credits
  | BlockContent
  | AccessibleImage
  | PublishingArtist
  | Legal
  | Faqs
  | Release
  | SanityFileAsset
  | TrackList
  | Artist
  | Slug
  | Seo
  | Publishing
  | Contact
  | Link
  | ContentSection
  | About
  | TwoColumn
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./lib/sanity/groq/index.ts
// Variable: AboutQuery
// Query: *[_type == "about"][0]
export type AboutQueryResult = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  overview: MetaDescription;
  part1: BlockContent;
  part2: TwoColumn;
  part3: BlockContent;
  part4: TwoColumn;
  part5: BlockContent;
} | null;
// Variable: ContactQuery
// Query: *[_type == "contact"][0]
export type ContactQueryResult = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  overview: MetaDescription;
  generalSection?: ContentSection;
  locations: Array<{
    type: string;
    name: string;
    phone?: string;
    _type: "location";
    _key: string;
  }>;
  listenLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  followLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  pressKit?: Link;
  demoSection?: ContentSection;
  syncSection?: ContentSection;
} | null;
// Variable: SEOQuery
// Query: *[_type == "seo"][0]
export type SEOQueryResult = {
  _id: string;
  _type: "seo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  description: string;
  twitterSite: string;
  keywords: string;
  followLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  cataloguePageTitle: string;
} | null;
// Variable: ArtistsQuery
// Query: *[_type == "artist" && defined(slug)] | order(name asc) {  _id,  slug,  name,  coverImage {    ...,    asset->{      ...,      metadata    }  }}
export type ArtistsQueryResult = Array<{
  _id: string;
  slug: Slug;
  name: string;
  coverImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: SanityImageMetadata | null;
      source?: SanityAssetSourceData;
    } | null;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;
// Variable: ArtistsStaticParamsQuery
// Query: *[_type == "artist" && defined(slug)] | order(name asc) {    slug  }
export type ArtistsStaticParamsQueryResult = Array<{
  slug: Slug;
}>;
// Variable: ArtistPageQuery
// Query: *[_type == "artist" && slug.current == $slug][0] {  ...,  coverImage {    ...,    asset->{      ...,      metadata    }  },  releases[]->{    title,    releaseReference,    releaseDate,    slug,  }}
export type ArtistPageQueryResult = {
  _id: string;
  _type: "artist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  overview: MetaDescription;
  coverImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: SanityImageMetadata | null;
      source?: SanityAssetSourceData;
    } | null;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  links?: Array<
    {
      _key: string;
    } & Link
  >;
  body?: BlockContent;
  releases: Array<{
    title: string;
    releaseReference: string;
    releaseDate: ReleaseDate;
    slug: Slug;
  }> | null;
} | null;
// Variable: FAQsQuery
// Query: *[_type == "faqs" && defined(questions)] | order(_createdAt asc)
export type FAQsQueryResult = Array<{
  _id: string;
  _type: "faqs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  category: string;
  slug: Slug;
  questions?: Array<
    {
      _key: string;
    } & QuestionAnswer
  >;
}>;
// Variable: ReleasesQuery
// Query: *[_type == "release" && defined(slug)] | order(releaseDate asc) {  ...,  artist[]->{name},  coverImage {    ...,    asset->{      ...,      metadata    }  },  trackList {    ...,    tracks[] {      ...,      artists[]->{name, slug}    }  }}
export type ReleasesQueryResult = Array<{
  _id: string;
  _type: "release";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  artist: Array<{
    name: string;
  }> | null;
  overview: MetaDescription;
  coverImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: SanityImageMetadata | null;
      source?: SanityAssetSourceData;
    } | null;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  productImages: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description: BlockContent;
  releaseDate: ReleaseDate;
  releaseReference: string;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
  trackList: {
    _type: "trackList";
    tracks: Array<{
      _key: string;
      _type: "track";
      name: string;
      number: number;
      length: string;
      file?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
        };
        _type: "file";
      };
      artists: Array<{
        name: string;
        slug: Slug;
      }> | null;
    }> | null;
  } | null;
  shopifyProductDigital: string;
  digitalProductFormat: string;
  shopifyProductPhysical: string;
  physicalProductFormat: string;
}>;
// Variable: ReleasesStaticParamsQuery
// Query: *[_type == "release" && defined(slug)] | order(releaseDate asc) {  slug}
export type ReleasesStaticParamsQueryResult = Array<{
  slug: Slug;
}>;
// Variable: ReleasePageQuery
// Query: *[_type == "release" && slug.current == $slug][0] {  ...,  artist[]->{name, slug},  productImages[] {    ...,    asset->{      ...,      metadata    }  },  trackList {    ...,    tracks[] {      ...,      artists[]->{name, slug}    }  }}
export type ReleasePageQueryResult = {
  _id: string;
  _type: "release";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  artist: Array<{
    name: string;
    slug: Slug;
  }> | null;
  overview: MetaDescription;
  coverImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  productImages: Array<{
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: SanityImageMetadata | null;
      source?: SanityAssetSourceData;
    } | null;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description: BlockContent;
  releaseDate: ReleaseDate;
  releaseReference: string;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
  trackList: {
    _type: "trackList";
    tracks: Array<{
      _key: string;
      _type: "track";
      name: string;
      number: number;
      length: string;
      file?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
        };
        _type: "file";
      };
      artists: Array<{
        name: string;
        slug: Slug;
      }> | null;
    }> | null;
  } | null;
  shopifyProductDigital: string;
  digitalProductFormat: string;
  shopifyProductPhysical: string;
  physicalProductFormat: string;
} | null;
// Variable: ReleaseTracklistQuery
// Query: *[_type == "release" && slug.current == $slug][0] {  productImages[0...1],  title,  trackList {    ...,    tracks[] {      ...,      artists[]->{name, slug}    }  }}
export type ReleaseTracklistQueryResult = {
  productImages: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  title: string;
  trackList: {
    _type: "trackList";
    tracks: Array<{
      _key: string;
      _type: "track";
      name: string;
      number: number;
      length: string;
      file?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
        };
        _type: "file";
      };
      artists: Array<{
        name: string;
        slug: Slug;
      }> | null;
    }> | null;
  } | null;
} | null;
// Variable: LegalStaticParamsQuery
// Query: *[_type == "legal" && defined(slug)] {  slug}
export type LegalStaticParamsQueryResult = Array<{
  slug: Slug;
}>;
// Variable: LegalQuery
// Query: *[_type == "legal" && defined(slug)]
export type LegalQueryResult = Array<{
  _id: string;
  _type: "legal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  overview: MetaDescription;
  englishTitle: string;
  englishContent: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  frenchTitle: string;
  frenchContent: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
}>;
// Variable: LegalPageQuery
// Query: *[_type == "legal" && slug.current == $slug][0]
export type LegalPageQueryResult = {
  _id: string;
  _type: "legal";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  overview: MetaDescription;
  englishTitle: string;
  englishContent: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  frenchTitle: string;
  frenchContent: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
} | null;
// Variable: PublishingQuery
// Query: *[_type == "publishing"][0]
export type PublishingQueryResult = {
  _id: string;
  _type: "publishing";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  overview: MetaDescription;
  creativeServicesSection?: ContentSection;
  scoreSection?: ContentSection;
  syncSection?: ContentSection;
  licenseRequestEmail: string;
} | null;
// Variable: PublishingArtistsQuery
// Query: *[_type == "publishingArtist" && defined(slug)] | order(name asc) {  _id,  slug,  name,  coverImage {    ...,    asset->{      ...,      metadata    }  },}
export type PublishingArtistsQueryResult = Array<{
  _id: string;
  slug: Slug;
  name: string;
  coverImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: SanityImageMetadata | null;
      source?: SanityAssetSourceData;
    } | null;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;
// Variable: PublishingArtistsStaticParamsQuery
// Query: *[_type == "publishingArtist" && defined(slug)] | order(name asc) {    slug  }
export type PublishingArtistsStaticParamsQueryResult = Array<{
  slug: Slug;
}>;
// Variable: PublishingArtistPageQuery
// Query: *[_type == "publishingArtist" && slug.current == $slug][0] {    ...,    coverImage {      ...,      asset->{        ...,        metadata      }    },  }
export type PublishingArtistPageQueryResult = {
  _id: string;
  _type: "publishingArtist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  overview: MetaDescription;
  coverImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata: SanityImageMetadata | null;
      source?: SanityAssetSourceData;
    } | null;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  projects?: Array<{
    name: string;
    href?: string;
    _type: "link";
    _key: string;
  }>;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
  body?: BlockContent;
  works?: TrackList;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "about"][0]\n': AboutQueryResult;
    '\n  *[_type == "contact"][0]\n': ContactQueryResult;
    '\n  *[_type == "seo"][0]\n': SEOQueryResult;
    '\n*[_type == "artist" && defined(slug)] | order(name asc) {\n  _id,\n  slug,\n  name,\n  coverImage {\n    ...,\n    asset->{\n      ...,\n      metadata\n    }\n  }\n}': ArtistsQueryResult;
    '\n  *[_type == "artist" && defined(slug)] | order(name asc) {\n    slug\n  }\n': ArtistsStaticParamsQueryResult;
    '*[_type == "artist" && slug.current == $slug][0] {\n  ...,\n  coverImage {\n    ...,\n    asset->{\n      ...,\n      metadata\n    }\n  },\n  releases[]->{\n    title,\n    releaseReference,\n    releaseDate,\n    slug,\n  }\n}': ArtistPageQueryResult;
    '\n*[_type == "faqs" && defined(questions)] | order(_createdAt asc)': FAQsQueryResult;
    '\n*[_type == "release" && defined(slug)] | order(releaseDate asc) {\n  ...,\n  artist[]->{name},\n  coverImage {\n    ...,\n    asset->{\n      ...,\n      metadata\n    }\n  },\n  trackList {\n    ...,\n    tracks[] {\n      ...,\n      artists[]->{name, slug}\n    }\n  }\n}': ReleasesQueryResult;
    '\n*[_type == "release" && defined(slug)] | order(releaseDate asc) {\n  slug\n}': ReleasesStaticParamsQueryResult;
    '\n*[_type == "release" && slug.current == $slug][0] {\n  ...,\n  artist[]->{name, slug},\n  productImages[] {\n    ...,\n    asset->{\n      ...,\n      metadata\n    }\n  },\n  trackList {\n    ...,\n    tracks[] {\n      ...,\n      artists[]->{name, slug}\n    }\n  }\n}': ReleasePageQueryResult;
    '\n*[_type == "release" && slug.current == $slug][0] {\n  productImages[0...1],\n  title,\n  trackList {\n    ...,\n    tracks[] {\n      ...,\n      artists[]->{name, slug}\n    }\n  }\n}': ReleaseTracklistQueryResult;
    '*[_type == "legal" && defined(slug)] {\n  slug\n}': LegalStaticParamsQueryResult;
    '\n*[_type == "legal" && defined(slug)]': LegalQueryResult;
    '\n  *[_type == "legal" && slug.current == $slug][0]\n': LegalPageQueryResult;
    '\n  *[_type == "publishing"][0]\n': PublishingQueryResult;
    '\n*[_type == "publishingArtist" && defined(slug)] | order(name asc) {\n  _id,\n  slug,\n  name,\n  coverImage {\n    ...,\n    asset->{\n      ...,\n      metadata\n    }\n  },\n}': PublishingArtistsQueryResult;
    '\n  *[_type == "publishingArtist" && defined(slug)] | order(name asc) {\n    slug\n  }\n': PublishingArtistsStaticParamsQueryResult;
    '\n  *[_type == "publishingArtist" && slug.current == $slug][0] {\n    ...,\n    coverImage {\n      ...,\n      asset->{\n        ...,\n        metadata\n      }\n    },\n  }\n': PublishingArtistPageQueryResult;
  }
}
